sudo: required
services:
  - docker

before_install:
  - docker build -t shreekarhegde/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shreekarhegde/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-2"
  env: "Dockerreact2-env"
  bucket_name: "elasticbeanstalk-us-east-2-047565902808"
  bucket_path: "docker-react-2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
